try{
    console.log("Start of try runs");
    console.log("End of try runs");
}catch(err){
    console.log("Catch is ignored ,because there are no error")
}